### ISSUE TITLE
Infografia de conceptos de gestion de proyectos de software

### ISSUE THREAD

**Issue by Aricel117** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Aricel117#2]
[Infografia Creaativa Proyecto Ilustrado Colorido.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Aricel117/files/12457975/Infografia.Creaativa.Proyecto.Ilustrado.Colorido.pdf)

**Comment by NoeliaGlez** [comment]
calificación: 20

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
